### ISSUE TITLE
Optional environment-variables for specifying timeouts & number of retries

### ISSUE THREAD

**Issue by iwilltry42** [trivago/exporter-chinacache#1]
**Problem**: Currently every http-request uses default settings for timeout and is only tried once, even though it might fail due to high latencies to Chinese servers.

**Objective**: Add optional environment variables to specify timeouts and number of retries for http-requests

**TODO:**
- main.go
    - [ ] query environment variables via `os.Getenv()`
    - [ ] evaluate values
    - [ ] pass values to constructor of client
- client.go
    - [ ] save values for retries/timeout
    - [ ] create a client for http-requests instead of using only `http.Get()`
    - [ ] use this client to create a GET-method with retries-/timeout-settings
